
version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
  storybook:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "npm run storybook"
    ports:
      - "6006:6006"
